name: Build on Pull Request
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build HOGi-Labs
    runs-on: ubuntu-latest
    env:
      VERSION_SUFFIX: "PR-${{ github.event.number }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Grant Permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Rename Jars
        run: for file in build/libs/*; do mv "$file" "${file/.jar/-${{ env.VERSION_SUFFIX }}.jar}"; done;

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Built Jars
          path: |
            ./build/libs/*.jar
          if-no-files-found: error
          compression-level: 0